Five Rerankers Added
KruxAI/ragbuilder pull request #51
Opened 2024-09-27 15:58 UTC by ashwinzyx

['cohere','jina','mixedbread-ai/mxbai-rerank-large-v1','flashrank','colbert']

2024-09-27 18:27 UTC, aravind10x requested changes

2024-09-27 18:27 UTC, aravind10x commented on src/ragbuilder/ragbuilder.py
> +os.environ['KMP_DUPLICATE_LIB_OK']='True'
What's the purpose of this?

2024-09-27 18:30 UTC, aravind10x commented on src/ragbuilder/langchain_module/retriever/retriever.py
Need to update line 40 as well to retrieve 100 docs from retriever when reranking is involved.

2024-09-27 19:58 UTC, ashwinzyx commented on src/ragbuilder/langchain_module/retriever/retriever.py
> +        code_string= f"""ranker = Reranker("mixedbread-ai/mxbai-rerank-base-v1", verbose=0)
fixed

2024-09-27 20:01 UTC, ashwinzyx commented on src/ragbuilder/ragbuilder.py
> +os.environ['KMP_DUPLICATE_LIB_OK']='True'
removed. Not needed anymore

2024-09-27 20:01 UTC, ashwinzyx commented on src/ragbuilder/langchain_module/retriever/retriever.py
>      if 'CrossEncoderReranker' in compressor_config:
modified to BAAI/bge-reranker-base

2024-09-27 20:02 UTC, ashwinzyx commented on src/ragbuilder/langchain_module/retriever/retriever.py
> +        code_string= f"""ranker = Reranker("mixedbread-ai/mxbai-rerank-base-v1", verbose=0)
fixed typo

2024-09-27 20:02 UTC, ashwinzyx commented on src/ragbuilder/langchain_module/retriever/retriever.py
Added to list

2024-09-28 10:25 UTC, aravind10x approved these changes

2024-09-28 10:50 UTC, merged